### ISSUE TITLE
raw: doesn't compile on linux/386

### ISSUE THREAD

**Issue by barakmich** [mdlayher/raw#1]
```
github.com/mdlayher/raw/raw_linux.go:285: undefined: syscall.SYS_SETSOCKOPT
```

In fact, it's not even defined in https://github.com/golang/sys/blob/master/unix/zsysnum_linux_386.go either... the closest reason I can find is https://github.com/golang/sys/blob/master/unix/syscall_linux_386.go#L186

**Comment by mdlayher** [comment]
Should be fixed by: https://github.com/mdlayher/raw/commit/b730b008e228b7a17bead43ec95edff75c2b082a.

**Comment by mdlayher** [comment]
`barakmich | mdlayher: yep, works fine`.

Closing.
