### ISSUE TITLE
add support capture specified direction ?

### ISSUE THREAD

**Issue by sheepbao** [mdlayher/raw#12]
like libcap can set capture direction by[ pcap_setdirection()]( https://linux.die.net/man/3/pcap_setdirection)

**Comment by mdlayher** [comment]
Seems reasonable to me. I imagine you could also do this with a BPF filter by checking if the destination MAC in an Ethernet frame belongs to your interface or not.

**Comment by sheepbao** [comment]
Thanks very much!

**Comment by mdlayher** [comment]
No problem. I could see this being potentially useful upstream, but let me know if you're able to accomplish this using BPF!
