### ISSUE TITLE
nil pointer dereference in raw_linux.go:162

### ISSUE THREAD

**Issue by jsimonetti** [mdlayher/raw#19]
Not sure if you want to fix it, since your program is pretty broken if you try to do this, but:
```
addr:=&raw.Addr{}
conn.WriteTo(b, addr)
```
results in a nil pointer dereference in raw_linux.go:162 (addr.HardwareAddr is not checked for nil)

**Comment by mdlayher** [comment]
Fixed: 43a0a12bddb04a0e38ff9b3caded53cbe6ffd6d7.
