### ISSUE TITLE
Undefined: bpf.Setter raw.go:88

### ISSUE THREAD

**Issue by JelmerDeHen** [mdlayher/raw#24]
I got the following error while go get github.com/mdlayher/arp.
```
$ go get github.com/mdlayher/arp
# github.com/mdlayher/raw
/bla/src/github.com/mdlayher/raw/raw.go:88:7: undefined: bpf.Setter
```
```
$ go version
go version go1.9.3 linux/amd64
```
I have now commented the line away locally which does work.

**Comment by mdlayher** [comment]
Your copy of golang.org/x/net is out of date. Clone the latest master and this should be fixed. Closing.
