### ISSUE TITLE
Build failing on Windows

### ISSUE THREAD

**Issue by d2g** [mdlayher/raw#25]
Hi,

Just a head up that the repo currently doesn't build on windows (I expect any that use raw_others.go). Error below.

go get github.com/mdlayher/raw
# github.com/mdlayher/raw
C:\go\src\github.com\mdlayher\raw\raw.go:115: too many arguments in call to listenPacket
        have (*net.Interface, uint16, *Config)
        want (*net.Interface, uint16)
C:\go\src\github.com\mdlayher\raw\timeval.go:17: cannot use int64(timeout / time.Second) (type int64) as type int32 in field value
C:\go\src\github.com\mdlayher\raw\timeval.go:18: cannot use int64(timeout % time.Second / time.Microsecond) (type int64) as type int32 in field value

Hope that's of some help.

**Comment by mdlayher** [comment]
Thanks for the report, fixed in https://github.com/mdlayher/raw/commit/d49579e77ad7a5760451ccca3bbbf88fdba2d193.

I'm sure you've seen this, but even if it does compile, this code is unimplemented on Windows as of now anyway. See #3 .
