### ISSUE TITLE
support centos6

### ISSUE THREAD

**Issue by qianfangyuan** [mdlayher/raw#46]
something wrong.
Centos6,Go 1.7

# github.com/mdlayher/raw
github.com/mdlayher/raw/raw_linux.go:88:14: f.SyscallConn undefined (type *os.File has no field or method SyscallConn)
github.com/mdlayher/raw/raw_linux.go:292:12: s.f.SetDeadline undefined (type *os.File has no field or method SetDeadline)
github.com/mdlayher/raw/raw_linux.go:296:12: s.f.SetReadDeadline undefined (type *os.File has no field or method SetReadDeadline)
github.com/mdlayher/raw/raw_linux.go:300:12: s.f.SetWriteDeadline undefined (type *os.File has no field or method SetWriteDeadline)

**Comment by mdlayher** [comment]
Please upgrade to Go 1.12. 

https://github.com/mdlayher/raw/blob/master/README.md#stability
