### ISSUE TITLE
What the different between the raw  and the github.com/google/gopacket/pcap ?

### ISSUE THREAD

**Issue by glennWang** [mdlayher/raw#55]
As the title say.

**Comment by mdlayher** [comment]
I don't use that library and thus cannot comment on the differences. This library can be used to send and receive Ethernet frames, among other things.

**Comment by glennWang** [comment]
Based on your lib,  if a simplified ip/stack  can be realised in order to bypass kernel IP/stack  and improve performance ？

My final purpose is to make a program like  LVS.
