### ISSUE TITLE
how to  capture lldp packets without promiscuous mode?

### ISSUE THREAD

**Issue by qinze118** [mdlayher/raw#60]
@mdlayher 
hello expert, I have an question that how to capture lldp packets without promiscuous mode,I want use your code handle this, please help me ,thanks!

**Comment by mdlayher** [comment]
This library doesn't set promiscuous mode by default, so opening a socket for LLDP Ethernet frames and reading them should just work.

This isn't the best place for questions, so closing. I'd recommend joining #networking on Gophers Slack or similar.

**Comment by qinze118** [comment]
thank you!
