### ISSUE TITLE
BPF BSD Header Completion in raw_bsd.go

### ISSUE THREAD

**Issue by bpillatsch** [mdlayher/raw#7]
Should the flag be 1 instead of 0? 1 will allow for MAC spoofing on the wire which i believe is what the comment is suggesting.

Line 202
`	// Do not automatically complete source address in ethernet headers
	if err := syscall.SetBpfHeadercmpl(fd, 0); err != nil {
		return 0, err
	}`

0 flag sets automatic header completion per BPF man page (read interface address will be written in place of frame provided to BPF for outgoing transaction)
`    BIOCSHDRCMPLT
     BIOCGHDRCMPLT
                     (u_int) Set or get	the status of the ``header complete''
		     flag.  Set	to zero	if the link level source address
		     should be filled in automatically by the interface	output
		     routine.  Set to one if the link level source address
		     will be written, as provided, to the wire.	 This flag is
		     initialized to zero by default.
`

**Comment by mdlayher** [comment]
Indeed, it appears I misread the documentation. Could you please send a PR? Thanks.

**Comment by bpillatsch** [comment]
Will do, just wanted to make sure i was understanding your intent :) I'm also wrapping up some promiscuous functionality into the BSD BPF and linux functions. I might wait on the PR for that to complete if thats ok.

**Comment by mdlayher** [comment]
Not sure exactly what you mean. Can you clarify?

**Comment by bpillatsch** [comment]
Disregard last, been a long week. I'll submit a PR shortly for this fix.

**Comment by mdlayher** [comment]
Looks like this is done.
